name: Build and Publish

on:
    push:
        tags:
        - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          7.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/BlazingQuartz
    - name: Build
      run: dotnet build --no-restore -p:Version=${{steps.tag.outputs.tag}} -p:PackageVersion=${{steps.tag.outputs.tag}} --configuration Release
      working-directory: src/BlazingQuartz
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      working-directory: src/BlazingQuartz
    - name: Publish BlazingQuartzApp
      run: dotnet publish -c Release --no-restore -o "../../app" -p:Version=${{steps.tag.outputs.tag}} -p:PackageVersion=${{steps.tag.outputs.tag}} "BlazingQuartzApp/BlazingQuartzApp.csproj"
      working-directory: src/BlazingQuartz
    - uses: actions/upload-artifact@v4
      with:
        name: BlazingQuartzApp
        path: app/
        
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
    - name: Download BlazingQuartzApp artifact
      uses: actions/download-artifact@v4
      with:
        name: BlazingQuartzApp
        path: app/
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: senolnar/arilquartzapp:latest, senolnar/arilquartzapp:${{steps.tag.outputs.tag}}
